server {
  listen 80;
  server_name _;
  charset utf-8;

  location = /legal-debate { return 301 /legal-debate/; }
  location /legal-debate/ {
    alias /usr/share/nginx/html/legal-debate/;
    sub_filter_once on;
    sub_filter '</head>' '<script src="/legal-debate/runtime.js"></script></head>';
    try_files $uri $uri/ /legal-debate/index.html;
  }

  location /legal-debate-api/ {
    proxy_pass http://api:8000/;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }
}
